server:
  port: 8099
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase: 
    change-log: classpath:/liquibase/master.xml
    enabled: true
  devtools: 
    restart:
          enabled: true
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
      cache: false
      mode: LEGACYHTML5
    